### PR TITLE
Stability Updates for Edge branch

### PR DESCRIPTION
**Pull request by joedf**
@TAC109 has done some great work updating and fixing the `edge` version with the directives feature.
See discussion: https://www.autohotkey.com/boards/viewtopic.php?f=6&t=65095

Making a pull request here. I'm not sure what Ahk2Exe should be under: fincs/Ahk2Exe, Lexikos/Ahk2Exe or should it be under ahkscript/Ahk2Exe or AutoHotkey/Ahk2Exe ?

### CODE REVIEW

**Comment by Lexikos** [comment]
How ready is this for release?

**Comment by TAC109** [comment]
I'd like to release at least one more beta before considering the edge branch “done”. May be a week or two before this is ready.

Cheers

**Comment by joedf** [comment]
@fincs We're planning to merge in the new changes and place the repo under `AutoHotkey/`.
Any thoughts or comments?

**Comment by fincs** [comment]
Heh, it's been a while. I would suggest cleaning up git history with an interactive rebase before merging this PR (especially @TAC109's commits). Also, looks like I have access to the AutoHotkey organization, so unless there are other plans, I could move my https://github.com/fincs/Ahk2Exe repo to it. Would that be OK?

**Comment by joedf** [comment]
@fincs Yes, definitely a long time! Hope everything's going well. I haven't written too much ahk myself for the past year.

I have sent you an invite for the `AutoHotkey/` organization, regardless. 
So, we should proceed with the following steps in this order?

1. Move to `AutoHotkey/`
2. Rebase
3. New PR
4. Merge

**Comment by fincs** [comment]
Looks like I confused ahkscript with AutoHotkey. Either way, I'm now in both :p
Yeah. I'm prepared to move Ahk2Exe to AutoHotkey. Shall I go ahead?

**Comment by joedf** [comment]
Alright-y, you're a go! 👍 
Closing this PR.

**Comment by fincs** [comment]
It is moved now.
EDIT: Looks like I can't access the settings tab anymore?

**Comment by joedf** [comment]
@fincs  Great! Also... Errr my bad! I mixed up the permissions. I just made you full-owner now; full access to everything. Let me know if that's not working either :p

**Comment by fincs** [comment]
Yeah, that fixed it, thanks!

**Comment by joedf** [comment]
Ok cool! How does the rebase work on here? I know on cmdline it's `git rebase`, but on the web I think we can just make the PR and choose a rebase-merge or something like that?

**Comment by fincs** [comment]
GitHub's rebase is not what I meant. I meant rewriting history, squashing commits, getting rid of redundant merge commits, etc. This is done using an [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History). Once the branch is cleaned up it can be merged into master.

**Comment by joedf** [comment]
So something like this? `git rebase master edge`
Also, `master` is ahead of `edge`. Should we squash only the merge commits in `edge`? Can you do this? If not, I can pick out the merge commits and put them in a list here. Or do you mean something like this:
```
git checkout master
git merge --squash edge
git commit
```

**Comment by fincs** [comment]
Nope. I mean `git rebase -i master`, which is an interactive rebase. Then, commits like c5ec7c7 and 92b83da can be squashed together (I suggest using `fixup`), or 
64f247d and b56ac1c, etc. Merge commits are removed automatically by rebases. Basically, what I'm trying to say is that history should be cleaned up (i.e. removing screwups or commits that fix typos or minor bugs, etc) before merging onto master.

This might also help: https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase

**Comment by joedf** [comment]
Gotcha! Thanks for your patience, clearly I've haven't used `rebase` much 😅
I'll go through it later tonight. Thanks again :]

**Pull request closed without merging**
